In [1]:
import numpy as np
Temperature_data=np.array([
    [20,30,32,31,33],
    [21,22,23,24,25],
    [25,28,30,34,35],
    [30,32,35,37,38]
])

Avg_temperature=np.mean(Temperature_data,axis=1)
print("The average temperature of cities are:",Avg_temperature)

The average temperature of cities are: [29.2 23.  30.4 34.4]


In [3]:
#to find the city with highest temperature
Avg_temperature=np.mean(Temperature_data,axis=1)

city_highest_avg_temperature=np.argmax(Avg_temperature)
cities=["mumbai","chennai","kolkata","Delhi"]
print("The highest temperature of cities is:",cities[city_highest_avg_temperature])




The highest temperature of cities is: Delhi


In [5]:
#calulate the temp anomlaies for each city 
temperature_anomalies=Temperature_data-Avg_temperature[:,np.newaxis]
print(temperature_anomalies)


[[-9.2  0.8  2.8  1.8  3.8]
 [-2.  -1.   0.   1.   2. ]
 [-5.4 -2.4 -0.4  3.6  4.6]
 [-4.4 -2.4  0.6  2.6  3.6]]
