In [1]:
#problem 1:Given a 20 Numpy array arr, extract all the even numbers from the array using advanced indexing.
import numpy as np
def extract_even_number(arr):
    return arr[arr%2==0]

#Test this function 
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
even_number=extract_even_number(arr)
print(even_number)



[2 4 6 8]


In [2]:
#problem2: given a 1D Numpy array, add 10 to each element and return the result using boardcasting
import numpy as np
def add_ten(arr):
    return arr+10
#test this function

arr=np.array([1,2,3,4,5,6])
result=add_ten(arr)
print(result)


[11 12 13 14 15 16]


In [4]:
#problem 3: Write a pyhton function that takes two 1D Numpy arrays arr1 and arr2 and computes thier element-wise multiplication using vectoraisation

import numpy as np
def elementwise_multiplication(arr1,arr2):
    return arr1*arr2

#Test the function
arr1=np.array([2,3,6,8,10])
arr2=np.array([10,33,4,55,76])

result=elementwise_multiplication(arr1,arr2)

print(result)





[ 20  99  24 440 760]


In [5]:
""""problem 4:write a python function that takes a 1D Numpy array arr and returns a new array
where each element is the square of the corresponding element in arr, but only if the element is 
greater than 5, for element less than or equal to 5, return 0."""

import numpy as np

def square_number(arr):
    result=np.where(arr>5,arr**2,0)
    return result

#Test the function 

arr=np.array([1,7,3,10,4,6])
result=square_number(arr)
print(result)


[  0  49   0 100   0  36]


In [6]:
#prolem 5: Given a 2D array data, write a python function that returns the sum of each row as a 1D array.

import numpy as np

def row_sum(data):
    return np.sum(data,axis=1)

#Test the function 

data=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
row_sum=row_sum(data)
print(row_sum)


[ 6 15 24]


In [7]:
#problem 6: Given a 1D Numpy array arr, replace all negative values with zeros

import numpy as np
def replace(arr):
    arr[arr<0]=0
    return arr

#Tedt the function
arr=np.array([1,-2,-3,4])
result=replace(arr)
print(result)

[1 0 0 4]
